# language of the project (csharp, python, rust, java, typescript, go, cpp, or ruby)
#  * For C, use cpp
#  * For JavaScript, use typescript
# Special requirements:
#  * csharp: Requires the presence of a .sln file in the project folder.
language: typescript

# whether to use the project's gitignore file to ignore files
# Added on 2025-04-07
ignore_all_files_in_gitignore: true
# list of additional paths to ignore
# same syntax as gitignore, so you can use * and **
# Was previously called `ignored_dirs`, please update your config if you are using that.
# Added (renamed)on 2025-04-07
ignored_paths:
  - dist
  - node_modules
  - .git

# whether the project is in read-only mode
# If set to true, all editing tools will be disabled and attempts to use them will result in an error
# Added on 2025-04-18
read_only: false


# list of tool names to exclude. We recommend not excluding any tools, see the readme for more details.
excluded_tools: []

# initial prompt for the project. It will always be given to the LLM upon activating the project
# (contrary to the memories, which are loaded on demand).
initial_prompt: |
  This is a TypeScript/React project called Sandpix Harada - a landing page generator application.
  
  Key technologies:
  - React 18 with TypeScript
  - Vite for build tooling
  - Tailwind CSS for styling
  - Supabase for backend (auth, database, storage)
  - Stripe for payment processing
  - GSAP for animations
  
  Project structure:
  - src/: Source code
  - supabase/: Supabase Edge Functions
  - public/: Static assets
  - scripts/: Utility scripts
  
  Please refer to CLAUDE.md for project-specific guidelines.

project_name: "sandpix_harada"